### PR TITLE
fix external deps

### PR DESCRIPTION
**Pull request by jhheider**
This isn't exactly pretty, but it fixes this problem:
```shell
echo 'import * as tea from "https://raw.github.com/teaxyz/lib/v0.3.0/mod.ts"' >foo.ts && deno check --unstable foo.ts
error: Relative import path "is-what" not prefixed with / or ./ or ../
    at https://raw.githubusercontent.com/teaxyz/lib/v0.3.0/src/utils/semver.ts:1:35

echo 'import * as tea from "../tea/lib/mod.ts"' >foo.ts && deno check --unstable foo.ts
Check file:///Users/jacob/foo/foo.ts
```

Basically, import maps don't externalize, meaning any consumer needs to provide our deps... that part seems deeply incorrect.

### CODE REVIEW

**Comment by jhheider** [comment]
Looking at the tests... I'm not actually sure how it worked before...

**Comment by mxcl** [comment]
I don't think it's unreasonable that consumers of the deno portion are expected to add our deps to their import map.

So this isn’t so much a fix as an opinion on how we should expect deno users to use libtea.

> Looking at the tests... I'm not actually sure how it worked before...

the import map is in `deno.json`

**Comment by mxcl** [comment]
quite possibly we should just do this.

one reason I am hesitant is it allows eg. tea/cli to define which version of eg. is-what is used rather than potentially having multiple.

I dunno. maybe that's a dumb concern.

**Comment by jhheider** [comment]
It was an unexpected outcome for me, certainly. I don't know off the top of my head of another Deno dep that requires side dependencies in this way.

**Comment by mxcl** [comment]
> I don't know off the top of my head of another Deno dep that requires side dependencies in this way.

yeah good point. ugh.

**Pull request merged**
